project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('squirrel.urls')),
]

squirrel/urls.py
from django.urls import path

from . import views

app_name = 'squirrel'

urlpatterns = [
        path('sightings/', views.index, name ='index'),
        path('map/', views.map, name = 'map'),
        path('sightings/add/', views.create_new, name = 'create new sighting'),
        path('sightings/stats/', views.stats, name = 'stats'),
        path('sightings/<unique_id>/', views.update, name='update'),
        ]

squirrel/models.py
from django.db import models
from django.utils.translation import gettext as _

class Squirrel(models.Model):
    
    latitude = models.FloatField(
            help_text=_('Latitude of Squirrel sighting'),
            blank = True,
    )

    longitude = models.FloatField(
            help_text=_('Longitude of Squirrel sighting'),
            blank = True,
    )

    unique_id = models.CharField(
            max_length = 100,
            help_text=_('Unique ID of Squirrel'),
    )

    AM = 'AM'
    PM = 'PM'
    
    SHIFT_CHOICES = [
            (AM, _('AM')),
            (PM, _('PM')),
    ]

    shift = models.CharField(
            max_length = 2,
            help_text=_('Shift of Squirrel'),
            choices=SHIFT_CHOICES,
            blank=True,
    )

    date = models.DateField(
            help_text = ('Date of record'),
            blank = True,
    )
    
    JUVENILE = 'Juvenile'
    ADULT = 'Adult'

    AGE_CHOICES = [
            (JUVENILE, _('Juvenile')),
            (ADULT, _('Adult')),
    ]

    age = models.CharField(
            max_length = 8,
            help_text=_('Age of Squirrel'),
            choices = AGE_CHOICES,
            blank=True,
    )
    
    BLACK = 'Black'
    CINNAMON = 'Cinnamon'
    GRAY = 'Gray'

    COLOR_CHOICE = (
            (BLACK,_('Black')),
            (CINNAMON,_('Cinnamon')),
            (GRAY,_('Gray')),
            )

    furColor = models.CharField(
            max_length=20,
            choices = COLOR_CHOICE,
            blank = True,
    )

    running = models.BooleanField(
            blank = True,
    )

    eating = models.BooleanField(
            blank = True,
    )

    climbing = models.BooleanField(
            blank = True,
    )
    
    def __str__(self):
        return self.unique_id

squirrel/forms.py
from django.forms import ModelForm
from .models import Squirrel


class CreateNewSighting(ModelForm):
    class Meta:
        model = Squirrel
        fields = '__all__'

class UpdateSighting(ModelForm):
    class Meta:
        model = Squirrel
        fields = [
            'latitude',
            'longitude',
            'unique_id',
            'shift',
            'date',
            'age',
            'furColor',
            'running',
            'eating',
            'climbing',
        ]

squirrel/views.py
from django.shortcuts import render
from squirrel.models import Squirrel
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse
from .forms import CreateNewSighting
from .forms import UpdateSighting
import random

def index(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels': squirrels,

            }
    return render(request, 'squirrel/index.html', context)

def update(request, unique_id):
    squirrel = get_object_or_404(Squirrel,unique_id = unique_id)
    form = UpdateSighting(request.POST or None, instance=squirrel)
    context = {
            'UpdateSighting':form,
    }
    if form.is_valid():
        squirrel = form.save(commit=False)
        squirrel.save()
        return redirect('/sightings/')
    else:
        context = {
            'form':form,
        }
        return render(request, 'squirrel/update.html', context)


def map(request):
    squirrels = Squirrel.objects.all()[:100]
    context = {
            'squirrels':squirrels,
            }
    return render(request,'squirrel/map.html', context)


def create_new(request):
    if request.method == 'POST':
        form = CreateNewSighting(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/sightings/')
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    else:
        form = CreateNewSighting()
        context = {
                'form':form,
            }
        return render(request, 'squirrel/create.html', context)

def stats(request):
     Number_of_Juvenile = Squirrel.objects.filter(age = 'Juvenile').count()
     Morning = Squirrel.objects.filter(shift = 'AM').count()
     BlackFur = Squirrel.objects.filter(furColor = "Black").count()
     Eatings = Squirrel.objects.filter(eating = True).count()
     Runnings = Squirrel.objects.filter(running = True).count()
     print(Runnings)
     context = {
            "Number_of_Juvenile":Number_of_Juvenile,            
            "Morning":Morning,
            "BlackFur":BlackFur,
            "Eatings":Eatings,
            "Runnings":Runnings,
            }
     return render(request,'squirrel/stat.html', context)

squirrel/templates/squirrel/create.html
<!doctype html>
<html>
	<body>
		<p> Add a Squirrel Sighting </p>
		<form action="/sightings/" method='POST'>
			{% csrf_token %}
				{% for field in form %}
					<li> {{field.label_tag}} {{field}} </li>
				{% endfor %}
				<button class="button" type="submit">Submit</button>
		</form>
	</body>
</html>

squirrel/templates/squirrel/detail.html
<html>
	<body>
	    This is detail about sighting:
	    <br> -Latitude: {{squirrel.latitude}} 
	    <br> -Longitude: {{squirrel.longitude}}
	    <br> -Squirrel Unique ID: {{squirrel.unique_id}}
	    <br> -Shift: {{squirrel.shift}}
	    <br> -Date: {{squirrel.date}}
	    <br> -Age: {{squirrel.age}}
	</body>
</html>

squirrel/templates/squirrel/index.html
<!doctype html>
<html>
	<body>
		<a href="{% url 'squirrel:create new sighting'%}">Create New Sighting</a>
		<p> List all sightings! </p>
		<ul>
			{% for squirrel in squirrels %}
			<li>
				<br> Unique ID: {{squirrel.unique_id}}
				<br> Date: {{squirrel.date}}
			        <a href= "{% url 'squirrel:update' squirrel.unique_id %}">Update</a >
			</li>
			{% endfor %}
		</ul>
	</body>
</html>

squirrel/templates/squirrel/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for squirrel in squirrels %}
          var point_lat_lon = [{{ squirrel.longitude }}, {{ squirrel.latitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

squirrel/templates/squirrel/stat.html
<!doctype html>
<html>
	<body>
		<p> General statistics about these sightings</p>
		<br>Number of Juvenile: {{Number_of_Juvenile}}
		<br>Morning Shift Number: {{Morning}}
		<br> Black Fur Squirrel Number: {{BlackFur}}
		<br> Eating Number: {{Eatings}}
		<br> Running Number: {{Runnings}}
	</body>
</html>

squirrel/templates/squirrel/update.html
<!doctype html>
<html>

<head>
	<p> View/Edit the Sighting!
	<form action='.' method="post">
		{% csrf_token %}
		{{ form.as_p}}
		<input type="submit" value="Update" class="btn btn-primary">

	</form>


</body>

</html>